version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./be:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend:
    container_name: frontend
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./fe:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
